//// <auto-generated/>
//#nullable enable

//// Suppress warnings about [Obsolete] member usage in generated code.
//#pragma warning disable CS0618

//using Microsoft.Extensions.Options;

//namespace Fido2.BlazorWebAssembly
//{

//    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Text.Json.SourceGeneration", "6.0.8.42425")]
//    public partial class FidoBlazorSerializerContext
//    {

//        private static global::System.Text.Json.JsonSerializerOptions s_defaultOptions { get; } = new global::System.Text.Json.JsonSerializerOptions()
//        {
//            DefaultIgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.Never,
//            IgnoreReadOnlyFields = false,
//            IgnoreReadOnlyProperties = false,
//            IncludeFields = false,
//            WriteIndented = false,
//        };

//        private static global::Fido2.BlazorWebAssembly.FidoBlazorSerializerContext? s_defaultContext;
//        public static global::Fido2.BlazorWebAssembly.FidoBlazorSerializerContext Default => s_defaultContext ??= new global::Fido2.BlazorWebAssembly.FidoBlazorSerializerContext(new global::System.Text.Json.JsonSerializerOptions(s_defaultOptions));

//        protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions { get; } = s_defaultOptions;

//        public FidoBlazorSerializerContext() : base(null)
//        {
//        }

//        public FidoBlazorSerializerContext(global::System.Text.Json.JsonSerializerOptions options) : base(options)
//        {
//        }

//        private global::System.Text.Json.Serialization.JsonConverter? GetRuntimeProvidedCustomConverter(global::System.Type type)
//        {
//            global::System.Collections.Generic.IList<global::System.Text.Json.Serialization.JsonConverter> converters = Options.Converters;

//            for (int i = 0; i < converters.Count; i++)
//            {
//                global::System.Text.Json.Serialization.JsonConverter? converter = converters[i];

//                if (converter.CanConvert(type))
//                {
//                    if (converter is global::System.Text.Json.Serialization.JsonConverterFactory factory)
//                    {
//                        converter = factory.CreateConverter(type, Options);
//                        if (converter == null || converter is global::System.Text.Json.Serialization.JsonConverterFactory)
//                        {
//                            throw new global::System.InvalidOperationException(string.Format("The converter '{0}' cannot return null or a JsonConverterFactory instance.", factory.GetType()));
//                        }
//                    }

//                    return converter;
//                }
//            }

//            return null;
//        }
//    }
//}
